### ISSUE TITLE
[Question] What terminal do you use to produce

### ISSUE THREAD

**Issue by kirillbobyrev** [MitchelPaulin/Walleye#13]
Hey! I've started implementing a chess engine in Rust and I was looking at the others for debugging/interface infrastructure, so I found yours! I really liked how you print the board using `colored`: this looks really cool and I wanted to implement something similar to have easier time looking at the positions in the engine (right now I have basic ASCII printing a-la python-chess/shakmaty). My question is: what terminal/fonts do you use? Any advice to make the output look like the one on your demo? This is what I currently get from running Walleye in my terminal:

<img width="140" alt="Screenshot 2021-12-30 at 10 50 35" src="https://user-images.githubusercontent.com/3352968/147741059-99dd644c-10d7-48b5-b7bc-cdf95737fae1.png">

**Comment by MitchelPaulin** [comment]
Hey Kirill,

I unfortunately no longer have access to the computer I used to take that picture. If I remember correctly it was Windows 10 running WSL2 using the Ubuntu terminal so it would be whatever the default font was. On my current system Ubuntu Mono on bash 5.1.8 is pretty close.

![image](https://user-images.githubusercontent.com/30714020/147775404-cfb8f05c-1f7d-457f-903d-6b6729e7341a.png)

**Comment by kirillbobyrev** [comment]
Thanks a lot! The approach you have is really neat, ASCII boards are really hard to read :( I tried just emoji but they're not readable either without the backgrounds (and even with them the white pieces have blank space within them, I guess that's the reason you're coloring the black Unicode symbols instead).

Thanks for your response, have a good day and good luck with your engine :)

**Comment by kirillbobyrev** [comment]
(just in case, I've used Fira Code + Alacritty)
