### ISSUE TITLE
50 move rule does not seem to be implemented

### ISSUE THREAD

**Issue by Dopplerian** [MitchelPaulin/Walleye#17]
For the following command:
`4k3/8/8/8/8/8/8/4K2R w - - 99 1`
The engine should only play 1 move and then draw in accordance to the [50 move rule](https://en.wikipedia.org/wiki/Fifty-move_rule), but it keeps playing anyway. I've checked the code and it doesn't seem to have this rule implemented anywhere.

**Comment by MitchelPaulin** [comment]
Thats correct, there is no check for the 50 move rule, only 3 fold is checked. This is on the list of things to do if I do get around to it but since it occurs so seldomly in real games that its low priority
