### ISSUE TITLE
Losing most games on time

### ISSUE THREAD

**Issue by mvanthoor** [MitchelPaulin/Walleye#5]
Hi Mitchel,

Author of Rustic here :) ( https://github.com/mvanthoor/rustic )

Your engine was mentioned on Talkchess.com, so I tried running a test against Rustic, version Alpha 1.1 (CCRL Blitz 1675). An often used time control for testing is 10s + 0.1s (so you can test 1000's of games without waiting a week). With this time control, WallEye 1.2.0 loses most games on time, often taking at least 5-6 seconds for the first move out of the opening book.

Because the time controls don't yet work correctly, the engine is essentially un-testable.

I hope you can spend some time fixing the time controls; I look forward to have another Rust engine in my testing pool.

Kind regards,
Marcel

**Comment by MitchelPaulin** [comment]
Hey Marcel

To make the engine smarter about time control is on the list of things to do, though a bit lower down behind making it play better in general. In the mean time, though it isn't ideal, if you are playing on very short time controls you can try lowering the depth of the engine https://github.com/MitchelPaulin/Walleye/blob/main/src/configs.rs#L2 to make it play faster, even lowering it from 6 to 5 results in a large move generation speedup. 

This projects original goal was learning rust and trying my hand at making an engine that could play legal chess, it being able to beat anyone was just a bonus, but it seems a lot of others have taken an interest in it which is great to see :). I hope I can find the time to implement this and I'll leave this issue open to track any progress towards it

**Comment by mvanthoor** [comment]
Hi Mitchel,

Here's an example of a very simple time-slice calculation in my engine, that works with 99.9% of the time controls.

https://github.com/mvanthoor/rustic/blob/master/src/search/time.rs

The only time it doesn't work is if the engine is out of base time, and the increment if extremely low, such as 0.05 seconds per move. In that case, the engine can use 80% of that (0.04 seconds), and then when it's out of time, it has only 0.01 seconds to finish and unwind the search. With this setup, that happens about 5-6 times per 1000 games.

I'm not sure if I'm ever going to fix this, because the absolute fastest time control I use for testing is 10s + 0.1s, and the engine never loses on time. CCRL Blitz uses 2m + 1s, so that is fine as well. At some point, when either using no time controls or ultra-ultra short increments, the engine wil have games where it rus out of time.

You can be sure that people on Talkchess are interested in new(er) engines, especially if they are not written in C or C++. If you want to have your engine tested by CCRL, it would be best to first fix the time control; they don't test with depth, because when doing so, you'd not be testing the engine, but the evaluation functions. (If both engines can reach depth X, regardless of time, it's the evaluation at depth X that is being tested, so that is no accurate measure of engine strength.)

**Comment by MitchelPaulin** [comment]
https://github.com/MitchelPaulin/Walleye/releases/tag/1.3.0

With the latest release the engine should now respond to time control (your time slice calculation function saved me a lot of fiddling around with values, thanks :) ). Switching over to an iterative deepening framework caused a large hit to the engines speed but I hope to address this through some type of PV line or transposition table optimization in the future. For now the engine is workable.

**Comment by SzotsGabor** [comment]
Thanks Mitchel for complying with test conditions so quickly. I'm going to start a tournament in a couple of days.

One more suggestion: to be able to switch off logging would be welcomed (not by only me).

**Comment by mvanthoor** [comment]
@MitchelPaulin 

Great to hear, thanks :) I'd appreciate the credits (as would anyone else who assisted somehow).

Don't worry about losing speed because of the iterative deepening. It works like:

```
dpeth 1
dpeth 1 2
dpeth 1 2 3
dpeth 1 2 3 4
dpeth 1 2 3 4 5
```

However, it makes time management much, much easier, because you always have SOME finished depth before your time runs out, and you just return the best move you have at that point (iterative deepening should keep the best move after each finished depth before starting the next).

Iterative deepening slows down the engine because of the repeated work it does, but after you add a TT, you can put your TT-move at the beginning of the move list, in your move ordering function. All the work iterative deepening does will be cached in the TT, alpha/beta will cut on the TT-move, and the engine will literally "fall" through all the depths down to the first it didn't yet calculate. So you're going to see this:

```
depth 1

drop
depth 1 2

drop
drop
depth 1 2 3


drop
drop
drop
depth 1 2 3 4
```

So this negates the speed loss, but keeps the easier time handling.

**Comment by SzotsGabor** [comment]
> Thanks Mitchel for complying with test conditions so quickly. I'm going to start a tournament in a couple of days.

Actually it has already started. If all goes well its results will be up at our site by next Sunday.

**Comment by mvanthoor** [comment]
@MitchelPaulin 

I ran a test against Rustic Alpha 1.

```
Score of WallEye 1.3.0 vs Rustic Alpha 1.1: 125 - 1051 - 824 [0.269]
...      WallEye 1.3.0 playing White: 53 - 458 - 489  [0.297] 1000
...      WallEye 1.3.0 playing Black: 72 - 593 - 335  [0.239] 1000
...      White vs Black: 646 - 530 - 824  [0.529] 2000
Elo difference: -174.1 +/- 11.8, LOS: 0.0 %, DrawRatio: 41.2 %
2000 of 2000 games finished.
```

No losses on time, at a time control of 10s+0.1s.

The result was fair. Rustic Alpha 1 is rated 1675, so Walleye 1.3.0 (roughly) has a rating of 1501 Elo. Note that Rustic Alpha 1 doesn't have capture extensions nor killer moves. The difference in rating seems to come from  PST's, and speed.

Your PST's seem to be based on A1 = 0, which is the same as Rustic. Maybe I'll see what replacing Walleye's PST's with Rustic Alpha 1's versions does for the rating. (Assuming you're now using different ones.)

**Comment by MitchelPaulin** [comment]
@mvanthoor 

It does look like a weak evaluation function was partly to blame. I tested with a new evaluation function and the engine was much stronger. It was enough of a difference that I think it warranted a new release. 

https://github.com/MitchelPaulin/Walleye/releases/tag/1.4.0

By popular demand logging is also disabled by default so you won't have to deal with your drive filling up with `walleye.log` files anymore :)

```
Score of walleye-1.4 vs rustic-alpha-1.1_32-bit-generic: 70 - 56 - 74 [0.535]
...      walleye-1.4 playing White: 39 - 27 - 34  [0.560] 100
...      walleye-1.4 playing Black: 31 - 29 - 40  [0.510] 100
...      White vs Black: 68 - 58 - 74  [0.525] 200
Elo difference: 24.4 +/- 38.4, LOS: 89.4 %, DrawRatio: 37.0 %
200 of 200 games finished.
```

**Comment by mvanthoor** [comment]
@MitchelPaulin 

Nice 👍🏻  I'll run another test. What PST's did you use / did you change in the evaluation?

**Comment by MitchelPaulin** [comment]
I adopted https://www.chessprogramming.org/PeSTO%27s_Evaluation_Function

**Comment by mvanthoor** [comment]
Nice update. Roughly 150 Elo improvement. 

```
Score of Walleye 1.4.0 vs Rustic Alpha 1.1: 257 - 347 - 396 [0.455]
...      Walleye 1.4.0 playing White: 148 - 152 - 200  [0.496] 500
...      Walleye 1.4.0 playing Black: 109 - 195 - 196  [0.414] 500
...      White vs Black: 343 - 261 - 396  [0.541] 1000
Elo difference: -31.4 +/- 16.7, LOS: 0.0 %, DrawRatio: 39.6 %
1000 of 1000 games finished.
```
